name: C/C++ CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:    

jobs:
  Bins:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - name: Download Kamek
      run: Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar" -OutFile Kamek.rar
      shell: pwsh
    - name: Download Code Warrior
      run: ${{ secrets.CODEWARRIOR_CMD }}
      shell: pwsh
    - shell: cmd
      run: |
        7z x *.rar
        rm -f *.rar
        mkdir output
    - name: Build Syati
      shell: cmd
      run: |
        python -m build USA
        rm -f *.d
        python -m build PAL
        rm -f *.d
        python -m build JAP
        rm -f *.d
        python -m build KOR
        rm -f *.d
        python -m build TWN
        mv *.bin output
    - name: Upload .bin Files
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Bins
        path: ${{ github.workspace }}/output
        
        
  Loaders:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - shell: pwsh
      run: |
       Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar" -OutFile Kamek.rar
       ${{ secrets.CODEWARRIOR_CMD }}
    - shell: cmd
      run: |
        7z x *.rar
        rm -f *.rar
    - run: mkdir dols
    - shell: pwsh
      run : |
       cd dols
       ${{ secrets.USA_CMD }}
       ${{ secrets.PAL_CMD }}
       ${{ secrets.JAP_CMD }}
    - shell: cmd
      run: |
        cd loader
        bash -c ./build_USA.sh
        rm -f *.o
        bash -c ./build_PAL.sh
        rm -f *.o
        bash -c ./build_JAP.sh
        rm -f *.o
    - name: Upload Loaders
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Loaders
        path: ${{ github.workspace }}/loader/out


  publish:
    if: github.ref == 'refs/heads/main'
    needs: [Bins, Loaders]
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          mkdir Release
          cd Release
          mkdir CustomCode
          mkdir Loaders
      - uses: actions/download-artifact@v2.0.10
        with: 
          name: Bins
          path: ${{ github.workspace }}/Release/CustomCode
      - uses: actions/download-artifact@v2.0.10
        with:
          name: Loaders
          path: ${{ github.workspace }}/Release/Loaders
      - shell: cmd
        run: |
          cd ${{ github.workspace }}/Release/Loaders
          rm -f *.xml
          cd ../
          7z a "${{ github.workspace }}/Syati.zip" *.* -r
          cd ../
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Auto"
          prerelease: true
          title: "Auto Build"
          files: |
            *.zip
