name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Bins:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - name: Curl Cache
      id: curl
      uses: actions/cache@v2.1.6
      with:
        path: C:\ProgramData\chocolatey\bin\curl.exe
        key: ${{ runner.os }}-curl
    - name: Install curl
      if: steps.curl.outputs.cache-hit != 'true'
      run: choco install curl --acceptlicense --confirm --verbose
      shell: cmd
    - name: Kamek Cache
      uses: actions/cache@v2
      id: kamek
      with:
        path: ${{ github.workspace }}/Kamek.rar
        key: ${{ runner.os }}-kamek
    - name: Download Kamek
      if: steps.kamek.outputs.cache-hit != 'true'
      run: curl -k -L https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar -o Kamek.rar
    - name: Code Warrior Cache
      uses: actions/cache@v2
      id: warrior
      with:
        path: ${{ github.workspace }}/${{ secrets.CODEWARRIOR_PATH }}
        key: ${{ runner.os }}-warrior
    - name: Download Code Warrior
      if: steps.warrior.outputs.cahce-hit != 'true'
      run: ${{ secrets.CODEWARRIOR_CMD }}
      shell: cmd
    - shell: cmd
      run: |
        7z x *.rar
        rm -f *.rar
        mkdir output
    - name: Build Syati
      shell: cmd
      run: |
        python -m build USA
        rm -f *.d
        python -m build PAL
        rm -f *.d
        python -m build JAP
        rm -f *.d
        mv *.bin output
    - name: Upload .bin Files
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Bins
        path: ${{ github.workspace }}/output
  Loaders:
    needs: Bins
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Curl Cache
      id: curl
      uses: actions/cache@v2.1.6
      with:
        path: C:\ProgramData\chocolatey\bin\curl.exe
        key: ${{ runner.os }}-curl
    - name: Install curl
      if: steps.curl.outputs.cache-hit != 'true'
      run: choco install curl --acceptlicense --confirm --verbose
      shell: cmd
    - run: mkdir dols
    - shell: cmd
      run : |
       cd dols
       ${{ secrets.USA_CMD }}
       ${{ secrets.PAL_CMD }}
       cd ../loader
       bash -c ./build_USA.sh
       rm -f *.o
       bash -c ./build_PAL.sh
       rm -f *.o
    - name: Upload Loaders
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Loaders
        path: ${{ github.workspace }}/loader/out
