name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:    

jobs:
  Bins:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.2
    - name: Download Kamek
      run: Poweshell Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar" -OutFile Kamek.rar
      shell: cmd
    - name: Download Code Warrior
      run: ${{ secrets.CODEWARRIOR_CMD }}
      shell: cmd
    - shell: cmd
      run: |
        7z x *.rar
        rm -f *.rar
        mkdir output
    - name: Build Syati
      shell: cmd
      run: |
        python -m build USA
        rm -f *.d
        python -m build PAL
        rm -f *.d
        python -m build JAP
        rm -f *.d
        python -m build KOR
        rm -f *.d
        python -m build TWN
        mv *.bin output
    - name: Upload .bin Files
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Bins
        path: ${{ github.workspace }}/output
        
        
  Loaders:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - shell: cmd
      run: |
       Poweshell Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/643925511906656257/829420068310876180/Kamek.rar" -OutFile Kamek.rar
       ${{ secrets.CODEWARRIOR_CMD }}
       7z x *.rar
       rm -f *.rar
    - run: mkdir dols
    - shell: cmd
      run : |
       cd dols
       ${{ secrets.USA_CMD }}
       ${{ secrets.PAL_CMD }}
       ${{ secrets.JAP_CMD }}
       cd ../loader
       bash -c ./build_USA.sh
       rm -f *.o
       bash -c ./build_PAL.sh
       rm -f *.o
       bash -c ./build_JAP.sh
       rm -f *.o
    - name: Upload Loaders
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Loaders
        path: ${{ github.workspace }}/loader/out
